image: gcc

build:
    stage: build
    before_script:
        - apt update && apt -y install cmake libgomp1
    script:
        - cd build/
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make
    artifacts:
        paths:
            - build/indivisible
